const employees = [
  {
    id: 1,
    name: "Ravi Kumar",
    email: "employee1@example.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        taskTitle: "Prepare sales report",
        taskDescription: "Compile monthly regional sales data",
        date: "2026-03-10",
        category: "Reporting",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Client follow-up",
        taskDescription: "Call pending leads",
        date: "2026-03-11",
        category: "Sales",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Update CRM",
        taskDescription: "Enter new contacts",
        date: "2026-03-12",
        category: "Data Entry",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 2,
    name: "Sneha Reddy",
    email: "employee2@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        taskTitle: "Design homepage banner",
        taskDescription: "Create promotional banner",
        date: "2026-03-09",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Fix UI bugs",
        taskDescription: "Resolve navbar issue",
        date: "2026-03-08",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Team meeting",
        taskDescription: "Discuss sprint backlog",
        date: "2026-03-07",
        category: "Meeting",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Prototype testing",
        taskDescription: "Test dashboard prototype",
        date: "2026-03-12",
        category: "Testing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    name: "Arjun Varma",
    email: "employee3@example.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        taskTitle: "Write API documentation",
        taskDescription: "Document authentication endpoints",
        date: "2026-03-06",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Code review",
        taskDescription: "Review merge requests",
        date: "2026-03-10",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Database backup",
        taskDescription: "Perform weekly backup",
        date: "2026-03-11",
        category: "Maintenance",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 4,
    name: "Pooja Sharma",
    email: "employee4@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        taskTitle: "Social media campaign",
        taskDescription: "Launch promotional campaign",
        date: "2026-03-05",
        category: "Marketing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Content writing",
        taskDescription: "Write blog on updates",
        date: "2026-03-09",
        category: "Content",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "SEO audit",
        taskDescription: "Analyze keyword performance",
        date: "2026-03-12",
        category: "SEO",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Newsletter draft",
        taskDescription: "Prepare newsletter",
        date: "2026-03-13",
        category: "Email Marketing",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 5,
    name: "Kiran Patel",
    email: "employee5@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        taskTitle: "Server monitoring",
        taskDescription: "Check CPU usage",
        date: "2026-03-08",
        category: "DevOps",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Deploy hotfix",
        taskDescription: "Deploy payment fix",
        date: "2026-03-09",
        category: "Deployment",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Security scan",
        taskDescription: "Run vulnerability scan",
        date: "2026-03-11",
        category: "Security",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Log cleanup",
        taskDescription: "Archive old logs",
        date: "2026-03-14",
        category: "Maintenance",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
];

const admin = [
  {
    id: 100,
    name: "Admin",
    email: "admin@example.com",
    password: "123",
    role: "admin",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  return employees;
};
